### ISSUE TITLE
InvalidClientTokenId

### ISSUE THREAD

**Issue by woutercouvaras** [ericraio/parse-server-simple-ses-adapter#7]
Hi,

I'm getting the above mentioned error when sending mails (e.g. password reset).  I've double checked that I'm on the correct version to take care of the v4 signature requirement (i.e. v1.0.6), which I am, but I'm still getting this error.

Is anyone else experiencing this issue?

**Comment by woutercouvaras** [comment]
Hi,

I've noticed that, although the repo is updated to use the correct version of node-ses, the version that is published on npm is not.  The published version is 1.0.6, where the repo is sitting at version 1.1.0.  The published version uses node-ses 1.2.0, but we need to be on version 3.0.2 at a minimum to avoid the above mentioned error.

Could I ask that you please publish the current version of the repo?

**Comment by ericraio** [comment]
sorry for such a delayed response, i will publish now
